export const SCREENS = {
  BOARD_POST: "BOARD_POST",
  BOARD_COMMENT: "BOARD_COMMENT",
  ADMIN_USERS: "ADMIN_USERS",
  ADMIN_ROLES: "ADMIN_ROLES",
  ADMIN_BOARDS: "ADMIN_BOARDS",
  ADMIN_ORGS: "ADMIN_ORGS",
  ADMIN_MENUS: "ADMIN_MENUS",
  ADMIN_CODES: "ADMIN_CODES",
  ADMIN_SCREENS: "ADMIN_SCREENS",
  SUPER_ADMIN_TENANTS: "SUPER_ADMIN_TENANTS",
  ADMIN_APPROVAL_DEF: "ADMIN_APPROVAL_DEF",
  MY_APPROVAL_LINE: "MY_APPROVAL_LINE",
  APPROVAL_DOCUMENT: "APPROVAL_DOCUMENT",
} as const;

export const ACTIONS = {
  CREATE: "CREATE",
  EDIT: "EDIT",
  DELETE: "DELETE",
  MANAGE: "MANAGE",
  REQUEST: "REQUEST",
  APPROVE: "APPROVE",
  REJECT: "REJECT",
  WITHDRAW: "WITHDRAW",
  CANCEL: "CANCEL",
} as const;

export type ScreenKey = (typeof SCREENS)[keyof typeof SCREENS];
export type ActionKey = (typeof ACTIONS)[keyof typeof ACTIONS];
